mysite/academic_adventure/urls.py
from django.urls import path

from . import views

app_name = 'academic_adventure'
urlpatterns = [
    path('', views.home, name='index'),
    path('home/', views.home, name='home'), #Home URL to show users their stats
    path('leaderboard/', views.leaderboard, name='leaderboard'), #Leaderboard URL for showing users their stats vs others
    path('events/', views.events, name='events'), #Leaderboard URL for showing users their stats vs others
    path('create/', views.create, name='create'), #Create URL for creating a new event
    path('create/<str:event_id>/', views.code, name='code'), #URL for a specific event, shows the code for a given event
    path('battle/', views.battle, name='battle'), #URL for the battle, reached by scanning an event. Passes in an event id
    path('leave/<str:code>', views.leave, name='leave'), #URL for leaving an event
    path('buy/<str:path>/<str:url>', views.buy_picture, name='buy'), #URL for buying a profile picture
    path('buy-potion/', views.buy_potion, name='buy-potion'), #URL for buying a potion
    path('shop/', views.shop, name='shop'), #Shop view
    path('changepic/', views.changePicture, name='changepic')

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register', include('register.urls')), #Includes the registration URLS
    path('academic-adventure/', include('academic_adventure.urls')), #Includes all URLS of our main app
    path('academic-adventure/', include('django.contrib.auth.urls')), #Includes login and log out URLS for academic-adventure app
    path('admin/', admin.site.urls), #Includes ability to access admin URLS
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/academic_adventure/forms.py
from django import forms
from .models import Event


class CreateForm(forms.ModelForm):
    """
    Form to create an event.
    Extends forms.ModelForm to use the django default form to create an object
    """
    class Meta:
        """
        Defines what should be shown in the form
        """
        model = Event #Selects model to use 
        #Input fields needed to create an event
        fields = ["name", "description", "date", "duration", "type", "longitude", "latitude"]
        #Labels for each input field
        labels = {"date": "Date and Time", #Date of the event
                  "duration": "Duration (Hours)", #Duration of the event
                  "longitude": "Longitude (Select from map)", #Location of the event
                  "latitude": "Latitude (Select from map)",
                  "name": "Name of event", #Name of the event
                  "type": "Type of event", #Type of event (Academic, Battle, Social, Sports)
                  "description": "Description of event"} #Description of the event
        
        #Widgets for the input boxes
        widgets = {
            "date": forms.DateTimeInput(attrs={"type":"datetime-local"}), #Adds a datetime picker to the date and time box
            "description": forms.Textarea(attrs={'rows': 3}),
        }

mysite/academic_adventure/views.py
from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required #Used to reject user entry to web page if not logged in
from .models import Event, CustomUser #Imports user defined models in the system
from .forms import CreateForm
from django.utils.crypto import get_random_string #Imports a random string generator for code generation
import random
import logging
import datetime
from django.utils import timezone

from .models import Event, Image
from .functions import get_user_positions, compare_positions, user_occupied, image_cost, populate_with_images, populate_unique_images

@login_required
def leaderboard(request):
    """
    View displaying leaderboards to show a user their stats against other people
    across campus.

    Keyword arguments:
    request -- HttpRequest object 
    """

    populate_with_images() #Populates the database with the initial profile pictures if not already populated


    #Gets all images available in store and ones the user does not own
    pictures = Image.objects.filter(in_store=True)
    user_pictures = request.user.pic_inventory.all() #Gets all of the users pictures
    profile_pic = request.user.profile_pic #Gets the users profile pic

    intelligence_position, athleticism_position, sociability_position = get_user_positions(request.user) #Gets users positions in each leaderboard

    context = {"scoreusers":sorted(CustomUser.objects.all(), key=lambda u:u.score, reverse = True)[:10], #Sorts users by overall score
            "intusers":sorted(CustomUser.objects.all(), key=lambda u:u.intelligence, reverse = True)[:5], #Sorts users by intelligence score
            "socusers":sorted(CustomUser.objects.all(), key=lambda u:u.sociability, reverse = True)[:5], #Sorts users by sociability score
            "athusers":sorted(CustomUser.objects.all(), key=lambda u:u.athleticism, reverse = True)[:5], #Sorts users by athleticism score
            "user":request.user,
            "intelligence_position": intelligence_position,
            "athleticism_position": athleticism_position,
            "sociability_position": sociability_position,
            "pictures": pictures,
            "user_pictures": user_pictures} #Passes user information and event information into the HTML form

    if profile_pic: #Checks if the user has a profile pic
        #If so set the users icon and image
        context["icon"] = profile_pic.icon 
        context["pic"] = profile_pic.img

    return render(request, 'academic_adventure/leaderboard.html', context) #Returns the leaderboard html page with the context passed in

@login_required
def home(request):
    """
    View for the map where the user can see their location and
    the location of events placed by gamekeepers

    Keyword arguments:
    request -- HttpRequest object 
    """

    populate_with_images() #Populates the database with the initial profile pictures if not already populated

    #Gets all images available in store and ones the user does not own
    pictures = Image.objects.filter(in_store=True)
    user_pictures = request.user.pic_inventory.all() #Gets all of the users pictures
    profile_pic = request.user.profile_pic #Gets the users profile pic

    intelligence_position, athleticism_position, sociability_position = get_user_positions(request.user) #Gets users positions in each leaderboard

    context = {"events":Event.objects.all(), #Gets all events in the database
                "user":request.user,
                "intelligence_position": intelligence_position,
                "athleticism_position": athleticism_position,
                "sociability_position": sociability_position,
                "pictures": pictures,
                "user_pictures": user_pictures} #Passes user information and event information into the HTML form
    
    if profile_pic: #Checks if the user has a profile pic
        #If so set the users icon and image
        context["icon"] = profile_pic.icon 
        context["pic"] = profile_pic.img

    return render(request, 'academic_adventure/home.html', context) #Returns the home html page with the context passed in

@login_required
def events(request):
    """
    View for the map where the user can see their location and
    the location of events placed by gamekeepers

    Keyword arguments:
    request -- HttpRequest object 
    """
    populate_with_images() #Populates the database with the initial profile pictures if not already populated


    current_datetime = timezone.now() # offset-awared datetime

    #Gets all images available in store and ones the user does not own
    pictures = Image.objects.filter(in_store=True)
    user_pictures = request.user.pic_inventory.all() #Gets all of the users pictures
    profile_pic = request.user.profile_pic #Gets the users profile pic

    valid_radius = 0.00036 #Maximum distance a user can be away from an event and participate
    intelligence_position, athleticism_position, sociability_position = get_user_positions(request.user) #Gets users positions in each leaderboard

    context = {"user":request.user,
               "intelligence_position": intelligence_position,
               "athleticism_position": athleticism_position,
               "sociability_position": sociability_position,
                "events":Event.objects.all(), #Gets all events in the database
                "current_time": current_datetime,
                "pictures": pictures,
                "user_pictures": user_pictures} #Passes user information and event information into the HTML form
    
    if profile_pic: #Checks if the user has a profile pic
        #If so set the users icon and image
        context["icon"] = profile_pic.icon 
        context["pic"] = profile_pic.img

    # Scanner code:
    if request.method == "POST": #If the user has scanned a QR code
        logging.info(request.POST.get("scancontent")) #Finds the event the QR code is for using stored contents of QR code
        
        #Gets user location from post request
        lat = request.POST.get("userlat")
        lng = request.POST.get("userlng")

        #Checks if user location has successfully been accessed
        if lng == "" or lat == "":
            context["message"] = "Error, can't get your location."
            return render(request, 'academic_adventure/events.html', context) #Shows scan page

        #Converts user location to decimal from string
        lat = Decimal(lat)
        lng = Decimal(lng)
        
        #Checks if the code is a digit and if the event ID being scanned exists
        if Event.objects.filter(code=request.POST.get("scancontent")).exists():
            scanned_event = Event.objects.get(code=request.POST.get("scancontent")) #Gets the scanned event

            #Gets the location for the event
            event_lng = scanned_event.longitude
            event_lat = scanned_event.latitude

            #Gets the distance the user is from the event scanned
            distance = compare_positions(lat, lng, event_lat, event_lng)
        
            #Checks if user is already currently participating in an event 
            # This only allows a user to be at one event at once
            if user_occupied(request.user): 
                context["message"] = "You are already signed up for an event. Try again when your current event finishes." #Displays message to user
            else:    
                if request.user not in scanned_event.members.all(): #Checks if user is not already registered for event
                    #Performs a distance check to check that the user is close enough to participate in the event
                    if distance > valid_radius:
                        context["message"] = "Too far away to participate in event" #Error message
            
                    #Checks if the scanned event is joinable (If the current time is between 10 minutes before the start of the event and 5 minutes after the start of the event)
                    elif not scanned_event.joinable():
                        context["message"] = "Can't join event, must be between 10 minutes before the start of the event and 5 minutes after the start."
        
                    else:
                        #If user isn't already registered for an event then apply bonus for attending in person event
                        reward = round(scanned_event.duration) #Gets the points reward for attending the event
                        if reward == 0: #If the reward is 0 then set it to 1 to ensure every event gives a points reward
                            reward = 1
                        
                        if request.user.stat_boost: #Checks if user has the stat boost potion
                            reward = reward * 2 #Multiplies the reward by 2, in line with the stat boost
                            request.session['used_potion'] = True
                            request.user.stat_boost = False #Removes potion from the user
                    
                        if scanned_event.type == "Sports":
                            request.user.athleticism += reward #If sports event then increase the users athleticism. Scaled by duration of the event
                            context["success"] = f"Successfully added to event: {scanned_event.name}. Athleticism increased by {reward} and points by {round((scanned_event.duration * 60) / 5)}!"
                        elif scanned_event.type == "Academic":
                            request.user.intelligence += reward #If academic event then add 1 to users intelligence. Scaled by duration of the event
                            context["success"] = f"Successfully added to event: {scanned_event.name}. Intelligence increased by {reward} and points by {round((scanned_event.duration * 60) / 5)}!"
                        elif scanned_event.type == "Social":

mysite/academic_adventure/templates/academic_adventure/code.html
<!DOCTYPE html>

<!--Loads static files of the project-->
{% load static %}

<!--Checks if the user is a gamekeeper-->
{% if not user.gamekeeper %}

<!--If not then return the user to the home page-->
<meta http-equiv="Refresh" content="0; url={% url 'academic_adventure:home' %}">

{% endif %}

<html>
    <head>
        <link rel="icon" href="{% static 'academic_adventure/favicon.ico'%}">
        <!--Includes bootstrap files-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <!--CSS for UI and navbar-->
        <link rel="stylesheet" type="text/css" href="{% static 'academic_adventure/ui.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'academic_adventure/profile.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'academic_adventure/code.css' %}">
        <script type="text/javascript" src="{% static 'academic_adventure/navbar.js' %}"> </script>
        <title>Code</title>
        <!--Scales the screen to the size of the viewport-->
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

        <!-- Script for the print button to set the print content -->
        <script>
          /**
           * Opens the print menu to print contents of a given div
           * @param divName: Name of the div to print the contents of
           */
          function printDiv(divName) {
            var printContents = document.getElementById(divName).innerHTML; //Gets the contents to print
            var originalContents = document.body.innerHTML;

            document.body.innerHTML = printContents;

            window.print(); //Opens the print window

            document.body.innerHTML = originalContents; //Restores HTML to original contents

            window.location.reload(); //Reloads the page to restore menu bar JS
          }
        </script>
    </head>

    <body>
      <!--HTML for navigation bar-->
      <div id="topContainer">
        <img src="{% static 'academic_adventure/logo.png' %}"  id="logo" alt="academic adventure logo">
        <!-- Navbar Button to toggle js that allows the navbarContainer to appear and disappear -->
        <button type="button" id="navbarButton"><img id="dropdownIcon" src="{% static 'academic_adventure/DropdownIcon.png' %}"></button>
        <!-- Profile Button that shows user's profile picture -->
        {% if icon %}
        <button type="button" id="profilePicture" data-bs-toggle="modal" data-bs-target="#profileModal"><img src="{% get_media_prefix %}{{icon}}"></button>
        {% else %}
        <button type="button" id="profilePicture" data-bs-toggle="modal" data-bs-target="#profileModal"><img src="{% static 'academic_adventure/user.png' %}"></button>
        {% endif %}

    </div>
        <div class="d-flex" id="navbarContainer">
          <ul class="navbar-nav ms-auto">
              <!-- Link to redirect to specified page -->
          <li class="nav-item active">
            <a class="nav-link iconBase" href="{% url 'academic_adventure:home' %}"><img class="icon" src="{% static 'academic_adventure/HomeIcon.png' %}">Home</a>
          </li>
          <!-- Bottom Padding for shop button -->
          <li class="nav-item">
            <a class="nav-link iconBase" href="{% url 'academic_adventure:events' %}"><img class="icon" src="{% static 'academic_adventure/EventsIcon.png' %}">Events</a>
            </li>
          <li class="nav-item">
            <a class="nav-link iconBase" href="{% url 'academic_adventure:shop' %}"><img class="icon" src="{% static 'academic_adventure/ShopIcon.png' %}">Shop</a>
        </li>
          <li class="nav-item">
            <a class="nav-link iconBase" href="{% url 'academic_adventure:leaderboard' %}"><img class="icon" src="{% static 'academic_adventure/LeaderboardIcon.png' %}">Rankings</a>
            </li>
            <li class="nav-item" id="logout">
                <a class="nav-link iconBase" href="{% url 'logout' %}"><img class="icon" src="{% static 'academic_adventure/LogoutIcon.png' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

     <!--Loads the QR code for the event-->
      {% load qr_code %}
      <div id="printContent">
        <img src="{% static 'academic_adventure/logo.png' %}"  id="logoPrint" alt="academic adventure logo">
        <div id="printContent0">
          <h1>Event: {{event.name}} </h1>
          <h2>{{event.date}}</h2>

          {% qr_from_text event.code size="L" %}
        </div>
    </div>

    </body>

        <!--Displays Print button for the event's QR code-->
      <div id="printContainer">
        <!-- <button type="text/css" media="print" id="printButton" onclick="printDiv('printableArea')" >Print</button> -->
        <input type="button" id="printButton" onclick="printDiv('printContent')" class="btn btn-outline-dark mt-auto" value="Print" />
      </div>
  
      <!--Displays members registered for the event-->
       <div id="memberContainer">
        <div class="text-center text-black pt-3">
          <h3>Members of event:</h3>
          {% if event_members|length == 0 %}
          <p>No users have currently joined this event.</p>
          {% else %}
          {% for member in event_members %}
          <p>{{member.username}}</p>
          {% endfor %}
          {% endif %}
       </div>
       </div>

        <!--Modal for profile page-->
        <div class="modal fade" id="profileModal" tabindex="-1" aria-labelledby="profileModal" aria-hidden="true">
          <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="profileModal">Profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <div class="row">
                      <div class="col-md-6" id="userProfilePic">
                          <h2>Hello {{user.username}}!</h2>
                          {% if pic %}
                          <img src="{% get_media_prefix %}{{pic}}">
                          {% else %}
                          <img src="{% static 'academic_adventure/userbig.png' %}">
                          {% endif %}
                          <br>
                          {% if user_pictures|length > 1 %}
                          <button type="button" data-bs-toggle="modal" data-bs-target="#inventoryModal" class="btn btn-outline-dark mt-auto">Change Avatar</button>
                          {% endif %}
                          <br>
                          <br>
                          <br>
                          <br>
                        </div>

                        <div class="col-md-6" id="userInfo">
                            <h2 class="display-6 fw-bolder">Your stats:</h2>
                            <h3>Overall score: {{user.score|floatformat:"2"}}</h3>
                            <h5 class = "px-3"><img src="{% static 'academic_adventure/academic.png' %}"></h5>
                            <h5><span>Intelligence: </span><span class="fw-bolder">{{ user.intelligence }}</span></h5>
                            <p><span>Position: #{{intelligence_position}}</span></p>
                  <h5 class = "px-3"><img src="{% static 'academic_adventure/social.png' %}"></h5>
                            <h5><span>Sociability: </span><span class="fw-bolder">{{ user.sociability }}</span></h5>
                            <p><span>Position: #{{sociability_position}}</span></p>
                            <h5 class = "px-3"><img src="{% static 'academic_adventure/sports.png' %}"></h5>
                            <h5><span>Athleticism: </span><span class="fw-bolder">{{ user.athleticism }}</span></h5>
                            <p><span>Position: #{{athleticism_position}}</span></p>
                            <h3>Points: {{user.points}}</h3>
                        </div>
                  </div>
              </div>
            </div>
          </div>
        </div>

        <!--Change profile picture modal-->
        <div class="modal fade" id="inventoryModal" tabindex="-1" aria-labelledby="inventoryModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="inventoryModalLabel">Change profile picture</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
          
                {% for pic in user_pictures %}

                <div class="text-center text-black pt-3">
                  <h4>{{pic.name}}</h4>
                  <img src="{{ pic.img.url }}">
                  <form method="post" action="/academic-adventure/changepic/">
                      {% csrf_token %} 
                      <button type="submit" name="picture" value="{{pic.id}}" class="btn btn-outline-dark mt-auto">Select</button>
                  </form>
                  </br>
                </div>

                
                {% endfor %}

              </div>
              </div>
            </div>
          </div>
        </div>
          <footer class="py-3">
            <div class="container"><p class="m-0 text-center text-black">Copyright &copy; Academic Adventure 2022</p></div>
          </footer>
</html>