mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register', include('register.urls')), #Includes the registration URLS
    path('academic-adventure/', include('academic_adventure.urls')), #Includes all URLS of our main app
    path('academic-adventure/', include('django.contrib.auth.urls')), #Includes login and log out URLS for academic-adventure app
    path('admin/', admin.site.urls), #Includes ability to access admin URLS
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/register/urls.py
from django.urls import path

from . import views

app_name = 'register'
urlpatterns = [
    path('', views.register, name='register'), #URL to register for the app
    path('privacy-policy/', views.privacy, name='privacy'), #URL for the privacy policy
]

mysite/register/models.py
from django.db import models

# Create your models here.

mysite/register/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

User = get_user_model()

class RegisterForm(UserCreationForm): 
    """
    Custom user registration form for users registering for the application.

    Extends UserCreationForm to use the default Django user creation form, which
    deals with invalid user input without requiring extra code.
    """
    def __init__(self, *args, **kwargs): 
        """
        Constructor for the user creation form.
        
        Methods contained within here are used to change the
        input boxes and their requirements
        """
        super().__init__(*args, **kwargs) #Inherits fields from the UserCreationForm

        #Customises the username input field
        self.fields['username'].widget.attrs.update({ 
            'class': 'form-input', 
            'required':'', 
            'name':'username', 
            'id':'username', #Sets id for easy css manuipulation
            'type':'text', 
            'placeholder':'username', 
            'maxlength': '16', #Sets a maximum username length
            'minlength': '6', #Sets a minimum username length
            }) 
        #Customises the first password input field
        self.fields['password1'].widget.attrs.update({ 
            'class': 'form-input', 
            'required':'', 
            'name':'password1', 
            'id':'password1', #Sets id for easy css manuipulation
            'type':'password', 
            'placeholder':'password', 
            'maxlength':'22',  
            'minlength':'8' #Sets a minimum password length, ensures security
            }) 
        #Customises the second password input field
        self.fields['password2'].widget.attrs.update({ 
            'class': 'form-input', 
            'required':'', 
            'name':'password2', 
            'id':'password2', #Sets id for easy css manuipulation
            'type':'password', 
            'placeholder':'confirm password', 
            'maxlength':'22',  
            'minlength':'8' #Sets a minimum password length, ensures security
            }) 

 
    username = forms.CharField(max_length=20, label=False) #Changes the username input field

    class Meta:
        """
        Defines what fields are in the form to create a new user
        """
        model = User #Uses the default user model to create a new user
        fields = ["username", "password1", "password2"] #Sets the fields of the form

mysite/register/views.py
from django.shortcuts import redirect, render
from .forms import RegisterForm
from django.contrib import messages

def register(request):
    """
    View to register a user in the database for the application

    Keyword arguments:
    request -- HttpRequest of the user
    """
    form = RegisterForm() #Default user creation form provided by django
    if request.method == "POST": #Checks if POST request
        credentials = RegisterForm(request.POST) #If so gets users entered credentials
        if credentials.is_valid(): #Checks if the users password and username is valid
            credentials.save() #If so save the username and password to the database
            messages.success(request, "Account created") #Add a success message to the screen
            return redirect("/register") #Redirects to the register page, where the user waits 3 seconds and then gets redirected to login page
        else:
            messages.error(request, "Error, password or username invalid.") #Display error message

    return render(request, 'register/register.html', {'form':form}) #Displays register HTML form with the Django user registration form
    
def privacy(request):
    """
    View to show the user the privacy policy for the application

    Keyword arguments:
    request -- HttpRequest of the user
    """
    return render(request, 'register/privacy-policy.html') #Renders the privacy policy HTML template

mysite/register/templates/register/register.html
<!DOCTYPE html>

<!--Loads the static CSS in the project-->
{% load static %}

<!--HTML page for the register page-->

<html>
    <head>
        <!--Scales the device for mobile-->
        <link rel="icon" href="{% static 'academic_adventure/favicon.ico'%}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <!--Includes bootstrap in the html-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <title>Register</title>
    </head>

    <body class="text-center" data-new-gr-c-s-check-loaded="14.1050.0" data-gr-ext-installed="">
        <img src="{% static 'academic_adventure/logo.png' %}" alt="" width="300" height="200">
        <div style="padding-bottom: 25px">
            <h1 class="h3 mb-3 font-weight-normal">Register:</h1>
            <form method="POST" actione="." class="text-center" id="register-form"> 
                {% csrf_token %} 
                
                    <!--Displays the form input boxes-->
                    <div class="sr-only" style="padding-top: 10px; padding-bottom: 10px"> 
                        {{form.username}}
                    </div>
                    <div class="sr-only" style="padding-top: 10px; padding-bottom: 10px">
                        {{form.password1}}
                    </div>
                    
                    <div class="sr-only" style="padding-top: 10px; padding-bottom: 10px"> 
                        {{form.password2}} 
                    </div> 
					
					<p style="padding-top: 10px; padding-bottom: 10px">By registering you agree to our<a class="nav-link" href="{% url 'register:privacy' %}">privacy policy</a></p>
            
                    <!--Checks if there are any messages to display-->
                    {% if messages %}
        
                    {% for message in messages %}
                 
                    <!--Display the error message if exists-->
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    
                    <!--Display the success message if exists-->
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                        <p>Redirecting...</p>
                        <!--Redirects the user to the login page after 2.5 seconds-->
                        <meta http-equiv="refresh" content="2.5; url=/academic-adventure/login"/>
                    </div>
                    {% endif %}
            
                    {% endfor %}
            
                    {% endif %}
            
                    <br><button type="submit" style="background-color: #b18b4f; border-color: #546474" class="btn btn-success">Register</button><br>
            
                    <p>Already got an account? <a href="{% url 'login' %}">Login</a></p> 
                </form> 
        </div>
        <div style="margin: auto; background-color: #535c74; padding-top: 25px; padding-bottom: 25px; color: white; border: 6px solid #b18b4f">
            <h1 class="h3 mb-3 font-weight-normal">Rules:</h1>
            <ul style="list-style-position: inside; padding-left: 0; text-align:center; font-size: 13px;">
                <li>Your username must be between 6 and 150 characters.</li>
                <li>Your username only contains letters, digits and @/./+/-/_.</li>
                <li>Your password must contain at least 8 characters and cannot be entirely numeric.</li>
                <li>Your password cannot be a commonly used password or too similar to your username.</li>
            </ul>
        </div>
    </body>
    <footer class="py-3">
        <div class="container"><p class="m-0 text-center text-black">Copyright &copy; Academic Adventure 2022</p></div>
      </footer>
</html>